### ISSUE TITLE
WIFI hotspot does not start

### ISSUE THREAD

**Issue by jtash** [AOSP-JF/issue_tracking_aosp#1]
WIFI hotspot tries to start but then shuts off immediately.  It keeps recycling on/off. Only way to stop is to reboot the phone.

**Comment by B--B** [comment]
Thanks for your report, I' we started to fix the bug but I' m busy in these days, hopefully this weekend I will have more time to work on it! 
PS: no need to reboot the phone, just enable and disable airplane mode and WiFi will work again!

**Comment by jtash** [comment]
thanks

**Comment by B--B** [comment]
Bug fixed with this commit: https://github.com/AOSP-JF/platform_frameworks_base/commit/e1b62865cc02997b2695626ee089dba5c22ba113
