### ISSUE TITLE
Recent apps list is missing delete button for all apps in the list

### ISSUE THREAD

**Issue by jtash** [AOSP-JF/issue_tracking_aosp#2]
When opening the recent apps list, the button to delete all of the listed apps is not visible.  The x to delete individual apps on the list shows, but not a master delete button.

**Comment by B--B** [comment]
This is not a bug mate, aosp does not have clear recent app list button, it's a feature that cm added to aosp code!

**Comment by jtash** [comment]
It's a nice feature. Would it be an issue to add this feature to this ROM?

**Comment by AntaresOne** [comment]
We'll discuss about it, meanwhile I close this issue report since like said by @B--B this is not a bug
