### ISSUE TITLE
Mount of sdcard1 is unstable

### ISSUE THREAD

**Issue by jtash** [AOSP-JF/issue_tracking_aosp#3]
I have found a few times that sdcard1 mount shows 0bytes and dissapears from the file manager.  I have to go into settings and select unount sdcard and then mount sdcard to get it back.

**Comment by B--B** [comment]
Please provide us more info, phone variant, sdcard type/fs and a log, or we cannot help.. Have you tried to format your sdcard and see if is something related to your sdcard? I use a 64 gb sdcard formatted in f2fs and on my test device the sdcard is in ext4 and works fine too... Fat is native so should work without problem, and one of our tester is using exfat as fs and afaik he never had an issue..

**Comment by jtash** [comment]
Hello,
  Sorry for the issue creation. I checked into it more at your request for additional information.  It seems to be a problem with Garmin Pilot rather than the ROM. The app has an option to move the database location on download (around 8gb) to external storage (ie extSdCard or sdcard1). It works fine on Lollipop 5.0 TW roms using extSdCard as a mount, but all CM12.1-based ROMs it crashes after moving the database.  On native CM12.1 it just crashes the program. On AICP 10 it locks the system up and on reboot it runs a whole system/data app upgrading cycle.  On your ROM it crashes the app and makes sdcard1 have a size of 0. If I unmount the “0” size sdcard then remount it then the card is visible again and no files are lost. My guess is that Garmin hasn’t made the app compatible with Lollipop 5.1 yet.
  The card is a Samsung micro sd class 10 120 GB formatted as exfat.

Is there any advantage/disadvantage to change the format of the microsd card to f2fs? If I format it as f2fs will it then only be readable/writable in the phone? Sometimes I take the card out of the phone and attach it to my windows laptop using a USB card reader. Would f2fs not be readable then on the pc?
Kind regards,
Joe

**Comment by B--B** [comment]
So it' s a issue related to Garmin, i can close this.. I use Sygic (everything on extsdcard) and works fine, regarding f2fs check the op, there' s a link with all the explanation, however, on my linux system works fine in my pc card reader, but i don't think that windows supports f2fs as filesystem

**Comment by jtash** [comment]
Thanks for the tip on Sygic. Yes I was able to access the card on my Ubuntu system. Looking forward to the next AOSP update.

---

Joseph S. Tash, Ph.D.
Professor
Dept. of Molecular & Integrative Physiology
Dept. of Urology
Past-President, American Society for Gravitational and Space Research
Mail Stop 3050
University of Kansas Medical Center
3901 Rainbow Blvd.
Hixon 1000
Kansas City, KS 66160
office: 913-588-7421
Fax: 913-588-7180
E-mail: jtash@kumc.edu

---

"The information transmitted in this communication is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission,  dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please destroy any copies, contact the sender and delete the material from any computer."

On July 18, 2015 7:07:00 AM B--B notifications@github.com wrote:

So it' s a issue related to Garmin, i can close this.. I use Sygic (everything on extsdcard) and works fine, regarding f2fs check the op, there' s a link with all the explanation, however, on my linux system works fine in my pc card reader, but i don't think that windows supports f2fs as filesystem

**Comment by jtash** [comment]
I just looked at Sygic.  Actually, Garmin Pilot is the aviation app, not the automobile app. Navigon, which is Garmin’s automobile app works fine on the extsdcard.
Best,
Joe
