### ISSUE TITLE
cannot save screenshots

### ISSUE THREAD

**Issue by jtash** [AOSP-JF/issue_tracking_aosp#5]
Gives error message saying there is not enough memory or that it is restricted by provider

**Comment by B--B** [comment]
Sorry but I' m busy with real life in these days, unfortunately I don't think that i will have time for work on aosp this and next week... However it's something related to permission, can be simply solved in two ways: Clean install + gapps, boot and complete the setup wizard logging with your gmail account and screenshot will work. Alternatively, you can install gapps, adb shell to your device, then switch to root with "su" (if needed) and type "am start -n com.google.android.setupwizard/.WelcomeUserActivity" this will launch setup wizard, complete in the same way and screenshot will work.

EDIT: If you have already installed gapps package no need to install another time, just run the commands on adb and will work.

**Comment by jtash** [comment]
Thanks, will give it a try.  I posted this as a new issue when I saw several other posts with the same problem.  Will the others be able to see your solution?
Best,
Joe

**Comment by B--B** [comment]
I was completely wrong, some resources/translation are missing, this means that for some languages works, for others not... No way to get screenshot if your language misses the string.. I'm fixing now, this can be closed, thanks for the report.
