### ISSUE TITLE
APN editing is broken in 07082015 ROM

### ISSUE THREAD

**Issue by jtash** [AOSP-JF/issue_tracking_aosp#6]
Cannot edit APN's in 07082015 ROM! This makes it impossible to activate LTE on CREDO mobile network. Need to be able to edit n.ispsn to n.w1.ispsn for the Sprint LTE network APN.

**Comment by B--B** [comment]
Have you tried to restore your apn config and then edit? No issue for me, i can create/delete/modify every single apn on my device

**Comment by jtash** [comment]
I tried copy a working config xml into the system/etc folder. Rebooting.  Still no apns show up to edit.

On August 9, 2015 1:16:37 PM B--B notifications@github.com wrote:

Have you tried to restore your apn config and then edit? No issue for me, i can create/delete/modify every single apn on my device

**Comment by jtash** [comment]
It was a totally clean install.

On August 9, 2015 1:16:37 PM B--B notifications@github.com wrote:

Have you tried to restore your apn config and then edit? No issue for me, i can create/delete/modify every single apn on my device

**Comment by B--B** [comment]
An list is the same as cm, I've picked their last commit as you can see by yourself, and i can edit every single apn and create/delete new apns. If you changed the xml then you must change permission too or will be unreadable

**Comment by jtash** [comment]
Would adding this to the build.prop work?

On August 9, 2015 2:13:03 PM B--B notifications@github.com wrote:

An list is the same as cm, I've picked their last commit as you can see by yourself, and i can edit every single apn and create/delete new apns. If you changed the xml then you must change permission too or will be unreadable

—
Reply to this email directly or view it on GitHubhttps://github.com/AOSP-JF/issue_tracking_aosp/issues/6#issuecomment-129226925.

#add this to build.prop
ril.sales_code=LOL
ro.csc.sales_code=LOL

**Comment by jtash** [comment]
I changed the r/w rights  of the apns-conf.xml to 777 and it made no difference. Still no APNs visible.

**Comment by jtash** [comment]
In AOSP-5.1.1-20150727-jflte.zip, APN editing works fine.  I tried dirty flashing AOSP-5.1.1-20150807-jflte.zip over AOSP-5.1.1-20150727-jflte and then the APNs are no longer visible, and not able to be edited. My device is a jfltespr on the CREDO mobile version of the Sprint network.So it requires the LTE APN to be n.w1.ispsn.

**Comment by B--B** [comment]
Fixed last night here: https://github.com/AOSP-JF/platform_vendor_aosp/commit/e679a1838dba1f1ac859bba60feba6ce582fe133 
This issue can ben closed, thanks for the report

**Comment by jtash** [comment]
Hi,
How do I incorporate the fix into the ROM?
Thanks,
Joe

On August 10, 2015 5:25:46 AM B--B notifications@github.com wrote:

Fixed last night here: AOSP-JF/platform_vendor_aosp@e679a18https://github.com/AOSP-JF/platform_vendor_aosp/commit/e679a1838dba1f1ac859bba60feba6ce582fe133
This issue can ben closed, thanks for the report
